//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using ABB.Robotics.ScreenMaker.Windows.Forms;
using System;


namespace ScreenMaker_2
{
    
    
    public class MainScreen : ABB.Robotics.ScreenMaker.Windows.Forms.ScreenForm
    {
        
        private ABB.Robotics.Tps.Windows.Forms.Button button2;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button3;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button5;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button6;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button8;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel2;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox1;
        
        private ABB.Robotics.Tps.Windows.Forms.GroupBox groupBox2;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel3;
        
        private ABB.Robotics.Tps.Windows.Forms.NumericUpDown numericUpDown3;
        
        private ABB.Robotics.Tps.Windows.Forms.NumericUpDown numericUpDown2;
        
        private ABB.Robotics.Tps.Windows.Forms.NumericUpDown numericUpDown1;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel6;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel5;
        
        private ABB.Robotics.Tps.Windows.Forms.TpsLabel tpsLabel4;
        
        private ABB.Robotics.Tps.Windows.Forms.Button button1;
        
        public MainScreen()
        {
            this.InitializeComponent();
        }
        
        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            ABB.Robotics.Tps.Resources.TpsResourceManager resources = new ABB.Robotics.Tps.Resources.TpsResourceManager(this.GetType().ToString());
            this.button1 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button2 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button3 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button4 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button5 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button6 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.button8 = new ABB.Robotics.Tps.Windows.Forms.Button();
            this.tpsLabel1 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel2 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox1 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.numericUpDown3 = new ABB.Robotics.Tps.Windows.Forms.NumericUpDown();
            this.numericUpDown2 = new ABB.Robotics.Tps.Windows.Forms.NumericUpDown();
            this.numericUpDown1 = new ABB.Robotics.Tps.Windows.Forms.NumericUpDown();
            this.tpsLabel6 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel5 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.tpsLabel4 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox2 = new ABB.Robotics.Tps.Windows.Forms.GroupBox();
            this.tpsLabel3 = new ABB.Robotics.Tps.Windows.Forms.TpsLabel();
            this.groupBox1.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // button1
            // 
            this.button1.BackColor = System.Drawing.Color.White;
            this.button1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button1.BackgroundImage")));
            this.button1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button1.ForeColor = System.Drawing.SystemColors.WindowText;
            this.button1.Location = new System.Drawing.Point(12, 29);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(104, 71);
            this.button1.Text = "1° Tequila";
            this.button1.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button1.WordWrap = true;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // button2
            // 
            this.button2.BackColor = System.Drawing.Color.White;
            this.button2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button2.BackgroundImage")));
            this.button2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button2.Location = new System.Drawing.Point(122, 27);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(115, 71);
            this.button2.Text = "2° Ginebra";
            this.button2.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button2.WordWrap = true;
            this.button2.Click += new System.EventHandler(this.button2_Click);
            // 
            // button3
            // 
            this.button3.BackColor = System.Drawing.Color.White;
            this.button3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button3.BackgroundImage")));
            this.button3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button3.Location = new System.Drawing.Point(122, 127);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(115, 71);
            this.button3.Text = "4° Granadina";
            this.button3.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button3.WordWrap = true;
            this.button3.Click += new System.EventHandler(this.button3_Click);
            // 
            // button4
            // 
            this.button4.BackColor = System.Drawing.Color.White;
            this.button4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button4.BackgroundImage")));
            this.button4.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button4.Location = new System.Drawing.Point(12, 127);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(104, 71);
            this.button4.Text = "3° Whiskey";
            this.button4.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button4.WordWrap = true;
            this.button4.Click += new System.EventHandler(this.button4_Click);
            // 
            // button5
            // 
            this.button5.BackColor = System.Drawing.Color.White;
            this.button5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button5.BackgroundImage")));
            this.button5.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button5.Location = new System.Drawing.Point(122, 230);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(115, 71);
            this.button5.Text = "6° Vodka";
            this.button5.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button5.WordWrap = true;
            this.button5.Click += new System.EventHandler(this.button5_Click);
            // 
            // button6
            // 
            this.button6.BackColor = System.Drawing.Color.White;
            this.button6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("button6.BackgroundImage")));
            this.button6.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.button6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.button6.Location = new System.Drawing.Point(12, 230);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(104, 71);
            this.button6.Text = "5° Ron";
            this.button6.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button6.WordWrap = true;
            this.button6.Click += new System.EventHandler(this.button6_Click);
            // 
            // button8
            // 
            this.button8.BackColor = System.Drawing.Color.DarkGreen;
            this.button8.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.button8.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11b;
            this.button8.ForeColor = System.Drawing.Color.White;
            this.button8.Location = new System.Drawing.Point(14, 226);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(293, 30);
            this.button8.Text = "Preparar bebida";
            this.button8.TextAlign = ABB.Robotics.Tps.Windows.Forms.ContentAlignmentABB.MiddleCenter;
            this.button8.WordWrap = true;
            this.button8.Click += new System.EventHandler(this.button8_Click);
            // 
            // tpsLabel1
            // 
            this.tpsLabel1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel1.Location = new System.Drawing.Point(100, 100);
            this.tpsLabel1.Multiline = true;
            this.tpsLabel1.Name = "tpsLabel1";
            this.tpsLabel1.Size = new System.Drawing.Size(123, 22);
            this.tpsLabel1.Title = "Seleccionadas";
            // 
            // tpsLabel2
            // 
            this.tpsLabel2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font11;
            this.tpsLabel2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel2.Location = new System.Drawing.Point(14, 33);
            this.tpsLabel2.Multiline = true;
            this.tpsLabel2.Name = "tpsLabel2";
            this.tpsLabel2.Size = new System.Drawing.Size(293, 45);
            this.tpsLabel2.Title = "Escoja en cada sección que bebida desea y luego presione en preparar bebida";
            this.tpsLabel2.WordWrap = true;
            // 
            // groupBox1
            // 
            this.groupBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox1.AutoScroll = false;
            this.groupBox1.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox1.Controls.Add(this.numericUpDown3);
            this.groupBox1.Controls.Add(this.numericUpDown2);
            this.groupBox1.Controls.Add(this.numericUpDown1);
            this.groupBox1.Controls.Add(this.tpsLabel6);
            this.groupBox1.Controls.Add(this.tpsLabel5);
            this.groupBox1.Controls.Add(this.tpsLabel4);
            this.groupBox1.Controls.Add(this.tpsLabel1);
            this.groupBox1.Controls.Add(this.tpsLabel2);
            this.groupBox1.Controls.Add(this.button8);
            this.groupBox1.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox1.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox1.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox1.Location = new System.Drawing.Point(293, 84);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(326, 283);
            this.groupBox1.Tag = null;
            this.groupBox1.Title = "Contador";
            this.groupBox1.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // numericUpDown3
            // 
            this.numericUpDown3.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numericUpDown3.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "Module1", "shot3")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.numericUpDown3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numericUpDown3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numericUpDown3.Location = new System.Drawing.Point(231, 139);
            this.numericUpDown3.Maximum = new decimal(new int[] {
                        6,
                        0,
                        0,
                        0});
            this.numericUpDown3.Minimum = new decimal(new int[] {
                        1,
                        0,
                        0,
                        0});
            this.numericUpDown3.Name = "numericUpDown3";
            this.numericUpDown3.Size = new System.Drawing.Size(76, 40);
            this.numericUpDown3.Value = new decimal(new int[] {
                        1,
                        0,
                        0,
                        0});
            // 
            // numericUpDown2
            // 
            this.numericUpDown2.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numericUpDown2.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "Module1", "shot2")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.numericUpDown2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numericUpDown2.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numericUpDown2.Location = new System.Drawing.Point(121, 139);
            this.numericUpDown2.Maximum = new decimal(new int[] {
                        6,
                        0,
                        0,
                        0});
            this.numericUpDown2.Minimum = new decimal(new int[] {
                        1,
                        0,
                        0,
                        0});
            this.numericUpDown2.Name = "numericUpDown2";
            this.numericUpDown2.Size = new System.Drawing.Size(76, 40);
            this.numericUpDown2.Value = new decimal(new int[] {
                        1,
                        0,
                        0,
                        0});
            // 
            // numericUpDown1
            // 
            this.numericUpDown1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.numericUpDown1.DataBindings.Add(new System.Windows.Forms.Binding("Value", new ABB.Robotics.ScreenMaker.Windows.Forms.SingleBindingSource(new ABB.Robotics.DataBinding.RapidDataObject("T_ROB1", "Module1", "shot1")), "Value", true, System.Windows.Forms.DataSourceUpdateMode.Never));
            this.numericUpDown1.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.numericUpDown1.ForeColor = System.Drawing.SystemColors.ControlText;
            this.numericUpDown1.Location = new System.Drawing.Point(14, 139);
            this.numericUpDown1.Maximum = new decimal(new int[] {
                        6,
                        0,
                        0,
                        0});
            this.numericUpDown1.Minimum = new decimal(new int[] {
                        1,
                        0,
                        0,
                        0});
            this.numericUpDown1.Name = "numericUpDown1";
            this.numericUpDown1.Size = new System.Drawing.Size(76, 40);
            this.numericUpDown1.Value = new decimal(new int[] {
                        1,
                        0,
                        0,
                        0});
            this.numericUpDown1.TextChanged += new System.EventHandler(this.numericUpDown1_TextChanged);
            // 
            // tpsLabel6
            // 
            this.tpsLabel6.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel6.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel6.Location = new System.Drawing.Point(231, 185);
            this.tpsLabel6.Multiline = true;
            this.tpsLabel6.Name = "tpsLabel6";
            this.tpsLabel6.Size = new System.Drawing.Size(76, 22);
            this.tpsLabel6.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel6.Title = "Tercera";
            // 
            // tpsLabel5
            // 
            this.tpsLabel5.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel5.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel5.Location = new System.Drawing.Point(121, 185);
            this.tpsLabel5.Multiline = true;
            this.tpsLabel5.Name = "tpsLabel5";
            this.tpsLabel5.Size = new System.Drawing.Size(81, 22);
            this.tpsLabel5.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel5.Title = "Segunda";
            // 
            // tpsLabel4
            // 
            this.tpsLabel4.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font12b;
            this.tpsLabel4.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel4.Location = new System.Drawing.Point(14, 185);
            this.tpsLabel4.Multiline = true;
            this.tpsLabel4.Name = "tpsLabel4";
            this.tpsLabel4.Size = new System.Drawing.Size(76, 22);
            this.tpsLabel4.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel4.Title = "Primera";
            // 
            // groupBox2
            // 
            this.groupBox2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left)));
            this.groupBox2.AutoScroll = false;
            this.groupBox2.AutoScrollMargin = new System.Drawing.Size(0, 0);
            this.groupBox2.Controls.Add(this.button5);
            this.groupBox2.Controls.Add(this.button6);
            this.groupBox2.Controls.Add(this.button3);
            this.groupBox2.Controls.Add(this.button4);
            this.groupBox2.Controls.Add(this.button2);
            this.groupBox2.Controls.Add(this.button1);
            this.groupBox2.Dock = System.Windows.Forms.DockStyle.None;
            this.groupBox2.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font10b;
            this.groupBox2.HorizontalAlign = ABB.Robotics.Tps.Windows.Forms.HorAlign.Left;
            this.groupBox2.LineStyle = ABB.Robotics.Tps.Windows.Forms.LineStyle.SingleLine;
            this.groupBox2.Location = new System.Drawing.Point(17, 39);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new System.Drawing.Size(249, 328);
            this.groupBox2.Tag = null;
            this.groupBox2.Title = "Bebidas";
            this.groupBox2.VerticalAlign = ABB.Robotics.Tps.Windows.Forms.VerAlign.Center;
            // 
            // tpsLabel3
            // 
            this.tpsLabel3.Font = ABB.Robotics.Tps.Windows.Forms.TpsFont.Font18b;
            this.tpsLabel3.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tpsLabel3.Location = new System.Drawing.Point(293, 39);
            this.tpsLabel3.Multiline = true;
            this.tpsLabel3.Name = "tpsLabel3";
            this.tpsLabel3.Size = new System.Drawing.Size(326, 47);
            this.tpsLabel3.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.tpsLabel3.Title = "BIENVENIDO";
            // 
            // MainScreen
            // 
            this.BackColor = System.Drawing.SystemColors.Control;
            this.Controls.Add(this.tpsLabel3);
            this.Controls.Add(this.groupBox2);
            this.Controls.Add(this.groupBox1);
            this.Text = "BarBot";
            this.Controls.SetChildIndex(this.groupBox1, 0);
            this.Controls.SetChildIndex(this.groupBox2, 0);
            this.Controls.SetChildIndex(this.tpsLabel3, 0);
            this.groupBox1.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
        }
        #endregion
        
        private void button7_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["resetSel"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Module1/resetSel").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button8_Click(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["start"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Module1/start").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
                // Calling ScreenOpen
                this.ShowScreen(typeof(Preparando));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button8_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void dataEditor1_TextChanged(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["shots"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Module1/shots").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in dataEditor1_TextChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button1_Click(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button1_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button2_Click(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button2_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button4_Click(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button4_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button3_Click(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button3_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button6_Click(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button6_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button5_Click(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button5_Click", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void button7_Click_1(object sender, System.EventArgs e)
        {
            try
            {
                // Calling RapidDataWrite
                ABB.Robotics.ScreenMaker.Base.IApplicationVariable write_0 = this.ScreenServices.ApplicationVariables["shot1"];
                ABB.Robotics.ScreenMaker.Windows.Forms.DataManager.GetRapidData(this, "RAPID/T_ROB1/Module1/shot").Value = ((ABB.Robotics.Controllers.RapidDomain.IRapidData)(write_0.Value));
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in button7_Click_1", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        private void numericUpDown1_TextChanged(object sender, System.EventArgs e)
        {
            try
            {
            }
            catch (System.Exception ex)
            {
                ABB.Robotics.Tps.Windows.Forms.GTPUMessageBox.Show(this, null, ex.ToString(), "Unexpected Error in numericUpDown1_TextChanged", System.Windows.Forms.MessageBoxIcon.Hand, System.Windows.Forms.MessageBoxButtons.OK);
            }
        }
        
        #region Protected Methods
        protected override void OnInstall(ABB.Robotics.ScreenMaker.Base.IScreenServices services)
        {
            if ((services.ApplicationVariables.Count == 0))
            {
                // 
                // shot2
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable shot2 = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("shot2", "2", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // start
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable start = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("start", "True", typeof(ABB.Robotics.Controllers.RapidDomain.Bool));
                // 
                // off
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable off = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("off", "False", typeof(ABB.Robotics.Controllers.RapidDomain.Bool));
                // 
                // cero
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable cero = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("cero", "0", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // shot1
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable shot1 = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("shot1", "1", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // shot3
                // 
                ABB.Robotics.ScreenMaker.Base.ApplicationVariable shot3 = new ABB.Robotics.ScreenMaker.Base.ApplicationVariable("shot3", "3", typeof(ABB.Robotics.Controllers.RapidDomain.Num));
                // 
                // Store variables
                // 
                services.ApplicationVariables.Add("shot2", shot2);
                services.ApplicationVariables.Add("start", start);
                services.ApplicationVariables.Add("off", off);
                services.ApplicationVariables.Add("cero", cero);
                services.ApplicationVariables.Add("shot1", shot1);
                services.ApplicationVariables.Add("shot3", shot3);
            }
            base.OnInstall(services);
        }
        #endregion
    }
}
