<Project>
	<PropertyGroup>
		<MainScreenIndex>0</MainScreenIndex>
	</PropertyGroup>
	<ScreenMakerVersion>25.3</ScreenMakerVersion>
	<Type>FlexPendant</Type>
	<References />
	<Controller GUID="31094167-bc7f-4c0d-a871-2fd105ae225a" Name="PCDAVID" System="IRB140_6_81" />
	<AssemblyInfo>
		<Title></Title>
		<Description>Code generated by ScreenMaker - Internal version 25.3.11371.0</Description>
		<Company></Company>
		<Product></Product>
		<Copyright></Copyright>
		<Trademark></Trademark>
		<Version>6.16.25</Version>
	</AssemblyInfo>
	<TpsViewInfo>
		<Caption>Barbot App</Caption>
		<MenuImageName>tpu-Operator32.png</MenuImageName>
		<TaskbarImageName>tpu-Operator32.png</TaskbarImageName>
		<StartPanelLocation>1</StartPanelLocation>
		<ViewType>1</ViewType>
		<StartupType>1</StartupType>
	</TpsViewInfo>
	<ApplicationVariables>
		<Variable Name="shot2" Value="2" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="start" Value="True" ValueType="ABB.Robotics.Controllers.RapidDomain.Bool,ABB.Robotics.Controllers.PC" />
		<Variable Name="off" Value="False" ValueType="ABB.Robotics.Controllers.RapidDomain.Bool,ABB.Robotics.Controllers.PC" />
		<Variable Name="cero" Value="0" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="shot1" Value="1" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
		<Variable Name="shot3" Value="3" ValueType="ABB.Robotics.Controllers.RapidDomain.Num,ABB.Robotics.Controllers.PC" />
	</ApplicationVariables>
	<ItemGroup />
	<ItemGroup>
		<Compile Include=".\MainScreen.view">
			<Link>MainScreen.view</Link>
		</Compile>
		<Compile Include=".\Preparando.view">
			<Link>Preparando.view</Link>
		</Compile>
		<Compile Include=".\Terminado.view">
			<Link>Terminado.view</Link>
		</Compile>
	</ItemGroup>
	<StartVirtualFlexPendant>False</StartVirtualFlexPendant>
	<FPSDKInfo>
		<Version>6.16.25</Version>
	</FPSDKInfo>
	<WidgetInfo />
</Project>